server:
  port: 8180
spring:
#  application:
#    name: Citizens-Server
#  eureka:
#    client:
#     serviceUrl:
#        defaultZone: http://localhost:8888
#    instance:
#        preferIpAddress: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    log-statement: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/citizens
    username: postgres
    password: postgres
  cloud:
    openfeign:
      client:
        config:
          weather-service:
            url: http://localhost:8080/weather
          salary-service:
            url: http://localhost:8081/salary

